version: "3.9"

services:
  postgres:
    container_name: postgres_local
    build:
      dockerfile: Dockerfile
      context: ./database
    environment:
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: officezip
    ports:
      - "5432:5432"
    volumes:
      - ./database/config/postgresql.conf:/var/lib/postgresql/data_custom/postgresql.conf
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: postgres -c config_file=/var/lib/postgresql/data_custom/postgresql.conf
    restart: always

  redis:
    container_name: redis_local
    build:
      dockerfile: Dockerfile
      context: ./redis
    volumes:
      - ./redis/config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    ports:
      - "6379:6379"
    restart: always

  minio:
    container_name: minio_local
    image: quay.io/minio/minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # MinIO Console
    environment:
      MINIO_ROOT_USER: admin
      MINIO_ROOT_PASSWORD: admin123
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"
    restart: always

volumes:
  minio_data:
