spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/chakgalpi
    driver-class-name: org.postgresql.Driver
    username: devuser
    password: devpass

  data:
    redis:
      port: 6379
      host: localhost
      password: redis@local

  jpa:
    database: postgresql
    defer-datasource-initialization: true
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform

  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(emQRpDeEngOGgdW6LAeM6VZ06kFnITy344QfEDQtR3RbNCe6TJG1Ke5z9TPkALjBIgcyk8T8r+0Cw6DNWWdhIQ==)
    password: ENC(7FK79Z/Ux7eQO0t3hOlGYatxOs6QykvyvucHcxQk1LS56h9CriShBCR2kSpx2I+V8Wj5+0d2evyAlz9kKaQxRQ==)

cors-config:
  allowed-origin-pattern:
    - http://localhost:2999
    - http://localhost:3000
    - http://localhost:5173
    - http://211.236.39.250:18088
    - http://211.236.39.250:18090

jwt:
  secret: c2lsdmVy0dXRvcmlhbbmluZS10ZWNoLXNwcmluZy1ib290LWp3dC1C1ib290LWp3dC10dX1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZyRvcmlhbC1zZWNyZXQK
  access-token-expiration: 31536000
  refresh-token-expiration: 31536000
#  access-token-expiration: 86400
#  refresh-token-expiration: 1209600

jasypt:
  password: chakgalpi.encrypt
  encryptor:
    bean: jasyptEncryptor
    algorithm: PBEWithHMACSHA512AndAES_256
    property:
      prefix: ENC(
      suffix: )
